### PR TITLE
Updated dependencies

### LINKED ISSUE #33: Rebuild request
Please rebuild phar to supress php warnings about switch statements.
The warning comes from composer/composer package, and it was fixed in later version.
I'm making this request for purely esthetic reasons, since I want to use your tools in php workshops.

```
$> workshop-manager add learnyouphp                                                                                                                                                                                                                    

PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///usr/local/bin/workshop-manager/vendor/composer/composer/src/Composer/DependencyResolver/RuleSetGenerator.php on line 286

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///usr/local/bin/workshop-manager/vendor/composer/composer/src/Composer/DependencyResolver/RuleSetGenerator.php on line 286
 Successfully installed "learnyouphp"
```

Also, very good job, if phpschool.io didn't exist, I'd make the initiative myself :+1:

### PR DESCRIPTION
**Pull request by ivanpepelko**
Should resolve [this](https://github.com/php-school/workshop-manager/issues/33) issue.

### CODE REVIEW

**Comment by AydinHassan** [comment]
Thank you @ivanpepelko - let's see if the auto build still works 😄

**Comment by AydinHassan** [comment]
Indeed it does not: https://travis-ci.org/php-school/workshop-manager/jobs/494492159 
I will take a look.

**Comment by AydinHassan** [comment]
@ivanpepelko looks like its built now - so hopefully you should be able to self update now!

**Comment by ivanpepelko** [comment]
Works! :D

**Pull request merged**
